made20150715/config/routes.rb
Rails.application.routes.draw do
  get 'clubs' => 'clubs#clubs'

  get 'clubs/clubs_category'

  get 'club_view' => 'clubs#club_view'

  get 'club_create' => 'clubs#club_create'

  get 'clubs/club_application'
  
  root 'pages#home' 

  post 'shared/error_messages'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  match 'auth/:provider/callback', to: 'sessions#facebook_create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]      
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get "/:category" => "clubs#clubs_category"
  
  resources :users

end

made20150715/app/models/club.rb
class Club < ActiveRecord::Base
	belongs_to :user

	validates :name, presence: true
	validates :manager, presence: true
	validates :category, presence: true
end

made20150715/app/models/user.rb
class User < ActiveRecord::Base
  has_many :clubs

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.email = "ThisisSample@naver.com"
      user.password = "password"
      user.save!
    end
  end
end

made20150715/app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def club_application
  end

  def club_create
  end

  def clubs
  	@clubs = Club.all.paginate(page: params[:page],  per_page: 9)
  end

  def clubs_category
  	case params[:category]
      when "play"
        @category = "연극"
      when "culture"
        @category = "문화"
      when "sports"
        @category = "체육"
      when "study"
        @category = "학술"
      when "helper"
        @category = "봉사"
      when "religion"
        @category = "종교"
    end
    @clubs = Club.where(category: @category).paginate(page: params[:page], per_page: 9)
  end

  def club_view
  	@clubs = Club.find_by(params[:id])
  end
end

made20150715/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

made20150715/app/controllers/sessions_controller.rb



      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      log_in (user)
      redirect_to (root_path)
      redirect_to clubs_path
    else
    end
    if user && user.authenticate(params[:session][:password])
    log_out
    redirect_to clubs_path
    redirect_to root_path
    session[:user_id] = nil
    session[:user_id] = user.id
    user = User.find_by(email: params[:session][:email].downcase)
    user = User.from_omniauth(env["omniauth.auth"])
  def create
  def destroy
  def facebook_create
  end
  end
  end
class SessionsController < ApplicationController
end

made20150715/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in (@user)
  		flash[:success] = "Welcome to the SejongClub!!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

made20150715/app/helpers/pages_helper.rb
module PagesHelper

end

made20150715/app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
    	session.delete(:user_id)
    	@current_user = nil
  	end
end

made20150715/app/helpers/shared_helper.rb
module SharedHelper
end

made20150715/app/helpers/users_helper.rb
module UsersHelper
end

made20150715/app/views/clubs/club_application.html.erb
<div class = "container">
	<form class="form-horizontal">
	  <fieldset>
	  <h2> 지 원 서 </h2>
	  <hr>
	    <div class="form-group">
	      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
	      <div class="col-lg-9">
	        <input type="text" class="form-control" id="inputEmail" placeholder="Email">
	      </div>
	    </div>

	    <div class="form-group">
	      <label for="inputPassword" class="col-lg-2 control-label">Password</label>
	      <div class="col-lg-9">
	        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
	        
	      </div>
	    </div>
	    
	    <div class="form-group">
	      <label for="textArea" class="col-lg-2 control-label">Textarea</label>
	      <div class="col-lg-9">
	        <textarea class="form-control" rows="3" id="textArea"></textarea>
	        <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
	      </div>
	    </div>
	    <div class="form-group">
	      <label class="col-lg-2 control-label">Radios</label>
	      <div class="col-lg-9">
	        <div class="radio">
	          <label>
	            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
	            Option one is this
	          </label>
	          <label>
	            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
	            Option two can be something else
	          </label>
	        </div>
	      </div>
	    </div>
	    <div class="form-group">
	      <label for="select" class=" col-lg-2 control-label">Selects</label>
	      <div class="col-lg-9">
	        <select class="form-control" id="select">
	          <option>1</option>
	          <option>2</option>
	          <option>3</option>
	          <option>4</option>
	          <option>5</option>
	        </select>
	        <select multiple="" class="form-control">
	          <option>1</option>
	          <option>2</option>
	          <option>3</option>
	          <option>4</option>
	          <option>5</option>
	        </select>
	      </div>
	    </div>

	    <div class="form-group">
		    <div class="checkbox">
		          <label>
		            <input type="checkbox"> Checkbox
		          </label>
		    </div>
		    <br>
		</div>

	    <div class="form-group">
	      <div class="col-lg-9 col-lg-offset-2">
	        <button type="reset" class="btn btn-default">Cancel</button>
	        <button type="submit" class="btn btn-primary">Submit</button>
	      </div>
	    </div>

	  </fieldset>
	</form>
</div>

made20150715/app/views/clubs/club_create.html.erb
<div class = "container">
	<form class="form-horizontal">
	  <fieldset>
	  <h2 id = "club_view"> 동아리 소개 내용</h2>
	    <div class="form-group">
	    <hr>
	      <label for="inputEmail" class="col-lg-2 control-label">동아리 이름</label>
	      <div class="col-lg-9">
	        <input type="text" class="form-control" id="inputEmail" placeholder="Email">
	      </div>
	    </div>

	    <div class="form-group">
	      <label for="inputPassword" class="col-lg-2 control-label">동아리 인원</label>
	      <div class="col-lg-9">
	        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
	   	  </div>
	   	</div>

	    <div class="form-group">
	      <label for="textArea" class="col-lg-2 control-label">동아리 소개 내용</label>
	      <div class="col-lg-9">
	        <textarea class="form-control" rows="3" id="textArea"></textarea>
	        <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
	      </div>
	    </div>

	    <div class="form-group">
	      <label class="col-lg-2 control-label">라디오 체크 생각 중</label>
	      <div class="col-lg-9">
	        <div class="radio">
	          <label>
	            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
	            Option one is this
	          </label>
	        </div>
	        <div class="radio">
	          <label>
	            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
	            Option two can be something else
	          </label>
	        </div>
	      </div>
	    </div>

	    <div class="form-group">
	      <label for="select" class="col-lg-2 control-label">동아리 분류</label>
	      <div class="col-lg-9">
	        <select class="form-control" id="select">
	          <option>연 극</option>
	          <option>문 화</option>
	          <option>학 술</option>
	          <option>봉 사</option>
	          <option>종 교</option>
	        </select>
	      </div>
	    </div>

	    <div class="form-group">
	      <div class="col-lg-8 col-lg-offset-2">
	        <button type="submit" class="btn btn-primary">제 출 하 기</button>
	        <button type="reset" class="btn btn-default">취 소 하 기</button>
	      </div>
	    </div>

	  </fieldset>
	</form>
</div>

made20150715/app/views/clubs/club_view.html.erb
<!-- Carousel
    ================================================== -->
<div class = "container">
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
	  
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	    <li data-target="#myCarousel" data-slide-to="1"></li>
	    <li data-target="#myCarousel" data-slide-to="2"></li>
	  </ol>


	  <div class="carousel-inner" role="listbox">
	    <div class="item active">
	      <!-- 나중에 이미지 대신 DB 넣어줄 곳-->
	      <%= image_tag("water.jpg") %>
	      <div class="container">
	        <div class="carousel-caption">
	          <h1>Example headline.</h1>
	          <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
	          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
	        </div>
	      </div>
	    </div>


	    <div class="item">
	      <!-- 나중에 이미지 대신 DB 넣어줄 곳-->
	      <%= image_tag("girl.jpg") %>
	      <div class="container">
	        <div class="carousel-caption">
	          <h1>Another example headline.</h1>
	          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
	        </div>
	      </div>
	    </div>


	    <div class="item">
	    	<!-- 나중에 이미지 대신 DB 넣어줄 곳-->
	      <%= image_tag("landscape.jpg") %>
	      <div class="container">
	        <div class="carousel-caption">
	          <h1>One more for good measure.</h1>
	          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
	        </div>
	      </div>
	    </div>
	  </div>


	  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div><!-- /.carousel -->
</div>


<div class = "container" id = "club_view">
	<div class="jumbotron">
		<!-- DB 넣어줄 곳-->
	    
	    <!--
	    <h1> <%= @clubs.name %> </h1>
	    <h3> <%= @clubs.category %> </h3>
	    <p> <%= @clubs.name %> 동아리에 오신걸 환영합니다~^0^</p>
	    -->
	    <p><a href= "/clubs/club_application" class="btn btn-primary btn-lg">지 원</a></p>
	</div>
</div>

made20150715/app/views/clubs/clubs.html.erb
<div class = "container" id = "club_list_cover">
	<% @clubs.reverse.each do |club| %>
			<div class="col-xs-8 col-sm-8 col-md-4 col-lg-4">
				<div class ="thumbnail">
					<!-- 나중에 이미지 대신 DB 넣어줄 곳-->
					<%= link_to image_tag("Category22.gif"), club_view_path %>	
				</div>
			</div>
	<% end %>

	<div id = "paginate">
		<%= will_paginate %>
	</div>
</div>

made20150715/app/views/clubs/clubs_category.html.erb
<div class = "container" id = "club_list_cover">
	<% @clubs.reverse.each do |club| %>
			<div class="col-xs-8 col-sm-8 col-md-4 col-lg-4">
				<div class ="thumbnail">
					<!-- 나중에 이미지 대신 DB 넣어줄 곳-->
					<%= link_to image_tag("Category22.gif"), club_view_path %>	
				</div>
			</div>
	<% end %>

	<div id = "paginate">
		<%= will_paginate %>
	</div>
</div>